apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wkuqs7oau-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wkuqs7oau-go 
  name: wkuqs7oau-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wkuqs7oau-go 
