apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wkuqs7oau-go 
  janus-idp.io/tekton: wkuqs7oau-go
  backstage.io/kubernetes-id: wkuqs7oau-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wkuqs7oau-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  